services:

  python-workspace:
    build:
      context: .
      dockerfile: Dockerfile.python
      args:
        - USER_NAME=k33g
    command: sleep infinity

  ollama:
    image: ollama/ollama:0.3.13
    ports:
      - 11434:11434

  download-llm:
    image: curlimages/curl:8.6.0
    entrypoint: ["curl", "ollama:11434/api/pull", "-d", "{\"name\": \"qwen2.5:0.5b\"}"]
    depends_on:
      ollama:
        condition: service_started