services:

  python-workspace:
    image: python:3.9
    command: sleep infinity

  ollama:
    image: ollama/ollama:0.5.3
    ports:
      - 11434:11434

  download-llm:
    image: curlimages/curl:8.6.0
    entrypoint: ["curl", "ollama:11434/api/pull", "-d", "{\"name\": \"qwen2.5:0.5b\"}"]
    depends_on:
      ollama:
        condition: service_started